### PR TITLE
remove maven

### PR DESCRIPTION
**Pull request by amiralig**
Remove maven from the IQ docker image. 
We probably have to do the same in the iq (insight-brain repo) as well.

With this change the instance of IQ comes up from what I saw after 
Screen Shot 2021-09-16 at 5 15 22 PM

### CODE REVIEW

**Review by mealingr — APPROVED** [review]
+1 lgtm

**Review by anna-d — APPROVED** [review]
+1

**Review by DennisWarren — APPROVED** [review]
+1 looks good to me

**Comment by amiralig** [comment]
fixed by https://issues.sonatype.org/browse/INT-5698

**Pull request closed without merging**
